name: eel-script
description: eel script
version: 0.0.0
repository: github
dependencies:
  eel-parser:   ">=0.0.0"
  eel-compiler: ">=0.0.0"
scripts:
  test:  sh scripts/test.sh
  shell: sh scripts/shell.sh
  clean: sh scripts/clean.sh
license: MIT
